[build]
publish = "dist"
command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"

[[redirects]]
  from = "/api"
  to = "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1"
  status = 200
  force = true